### ISSUE TITLE
关于代理转换的问题

### ISSUE THREAD

**Issue by GZ1903** [thank243/v2board_cc#3]
你好，代理手动填写经常出错，有没有一键订阅转换你的规则的代理呢。
  - { name: PROXY, type: trojan, server: EXAMPLE.COM, port: 10086, password: XXXXXXXX, udp: true, sni: XXXXXXX, skip-cert-verify: true }

**Comment by thank243** [comment]
使用订阅转换服务，添加list=true参数

**Comment by GZ1903** [comment]
你有什么好的订阅转换服务推荐嘛，可以直接转化用于该脚本的，网上的需要重写匹配规则才能特殊化匹配你脚本的格式吧。

**Comment by thank243** [comment]
使用的是标准clash格式，具体怎么转，请自行查找相关资料

**Comment by GZ1903** [comment]
十分感谢你的解答
